defaults:
  - _self_
  - data: hillstrom
  - model: gpt

seed: 10
prompt_type: sample_incontext
enum_x: False
use_samples: ipw
baseline_name: None

experiment_name: test
prompt_dir: $HOME/natural/llm_extraction/prompts/
save_path: $HOME/natural/data/
date_time: ${now:%Y-%m-%d}_${now:%H-%M-%S}
restore: False